server:
  port: 8080
  servlet:
    context-path: /lock

spring:
  redis:
    timeout: 6000ms
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
    password:

redis:
  lock:
    key: test